# Par치metros del entrenamiento
training:
  n: 50000
  n_cuad_lado: [2]
  pixeles_cuad: [25]
  ratio: [1]
  num_epochs: 500
  batch_size: 64
  learning_rate: 0.0005
  scheduler_name: None
  scheduler_params: None

# Par치metros generales del modelo
model:
  encoding_dim: 32
  loss_function: "mse"
  optimizer: "adam"

# Arquitectura del encoder
encoder:
  layers:
    - type: "conv2d"
      filters: 16
      kernel_size: 3
      stride: 2
      padding: 1
      activation: "relu"
    - type: "flatten"
    - type: "dense"
      dim: "${model.encoding_dim}"
      activation: "relu"

# Arquitectura del decoder
decoder:
  layers:
    - type: "dense"
      dim: 10000
      activation: "relu"
    - type: "unflatten"
      dim1: 25
      dim2: 25
      out_channels: 16
    - type: "conv2d_transpose"
      filters: 1
      kernel_size: 2
      stride: 2
      padding: 0
      activation: "sigmoid"

# Par치metros de la evaluaci칩n
testing:
  n: 1000
  batch_size: 32